import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/Navbar";
import { ThemeProvider } from "./context/ThemeContext";
import Footer from "./components/Footer/footer";
import AuthProvider from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthProvider>
        </ThemeProvider>
        <script src="//code.tidio.co/2ptymkyljlraxn5oip8wqz1pieww3ff7.js" async></script>
      </body>
    </html>
  );
}
